### ISSUE TITLE
Conda install gives version 2.5

### ISSUE THREAD

**Issue by bikashg** [sepandhaghighi/pycm#378] opened 2021-07-14 11:04 UTC
#### Description 
I used the conda install to install this package and get the 2.5 version of pycm even though conda page here `https://anaconda.org/sepandhaghighi/pycm` mentions version 3.1

#### Steps/Code to Reproduce
`conda install -c sepandhaghighi pycm`

#### Expected Behavior
version 3.1
#### Operating System
Ubuntu 20.04

#### Python Version
3.8.8

**Comment by sepandhaghighi** [comment] 2021-07-14 12:38
@bikashg Hi
I don't think the problem is PyCM, it's something related to conda cache.

My suggestions :
1- Clean your conda cache and lock files (take a look at [this link](https://docs.conda.io/projects/conda/en/latest/commands/clean.html))
2- Install a specific version of PyCM: `conda install -c sepandhaghighi pycm=3.1`

Best Regards

**Comment by bikashg** [comment] 2021-07-14 13:38
Thanks @sepandhaghighi for suggestions. Conda cache clean didn't help. Later, when I issued `conda install -c sepandhaghighi pycm=3.1`, I got the following error:

**Comment by sepandhaghighi** [comment] 2021-07-14 19:42
@bikashg 
It's a little weird!!
I tried to reproduce the bug and then solve it by updating conda : `conda update conda`
Please try it and give me some feedback.

Best Regards

**Comment by alirezazolanvari** [comment] 2021-08-24 20:38
@bikashg Thanks for noting this issue. It has been resolved by editing the readme file.  Please check the corresponding section [here](https://github.com/sepandhaghighi/pycm#installation).

**Closed by alirezazolanvari** 2021-08-24 20:38 UTC
